name: CI
on:
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Build
        run: pnpm run ci:build
      - name: Check Api
        run: pnpm run ci:check-api
