name: CI
on:
  push:
    branches:
      - "**"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
          cache: true
      - name: Install dependencies
        run: deno install --frozen
      - name: Check type
        run: deno task check-type

  test-node:
    strategy:
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
          cache: true
      - name: Install dependencies
        run: deno install --frozen
      - uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
      - name: Test
        run: deno task test:node
  test-deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
          cache: true
      - name: Install dependencies
        run: deno install --frozen
      - name: Test
        run: deno task test