name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    if: ${{github.repository_owner == 'asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          registry-url: https://registry.npmjs.org
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
          cache: true
      - name: Install dependencies
        run: deno install --frozen

      - name: Build
        run: deno task build
      - name: Publish-Jsr
        run: npx jsr publish
  publish-jsr:
    if: ${{github.repository_owner != 'asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Publish
        run: npx jsr publish
